# Generated by Django 5.0.1 on 2024-02-15 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('target_date', models.DateField()),
                ('currency', models.CharField(max_length=3)),
                ('LimitTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.limittype')),
                ('profileID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.PositiveBigIntegerField(unique=True)),
                ('expiration_date', models.DateField()),
                ('type', models.BooleanField()),
                ('money', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('currency', models.CharField(max_length=3)),
                ('profileID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='SavingsPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('current_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('profileID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_time', models.DateTimeField()),
                ('trader', models.CharField(max_length=100)),
                ('cardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.card')),
                ('transactionTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.transactiontype')),
            ],
        ),
    ]
